# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run','deploy','${_SERVICE}',
      '--image','${_IMAGE}',
      '--region','${_REGION}',
      '--allow-unauthenticated'
    ]

# 👇 Add this block so Cloud Build is happy when a custom service_account is used
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1
  _SERVICE: my-ml-api
  _PROJECT_ID: my-ml-project-474215
  _REPO: ml-repo
  _IMAGE: 'us-central1-docker.pkg.dev/my-ml-project-474215/ml-repo/my-ml-api:${SHORT_SHA}'

images:
  - 'us-central1-docker.pkg.dev/my-ml-project-474215/ml-repo/my-ml-api:${SHORT_SHA}'
